# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-21 07:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('price', models.CharField(max_length=50)),
                ('summary', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
