# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-21 09:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_package'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=20)),
                ('Email', models.CharField(max_length=20)),
                ('msg', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'contacts',
            },
        ),
    ]
