# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-21 09:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='fullname',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='contact',
            name='msg',
            field=models.CharField(max_length=100),
        ),
    ]
